name: Create new tag
on: [workflow_dispatch]
jobs:
  newtag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setting up node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install nerdbank-git-versioning
        run: npm install nerdbank-gitversioning -d

      - name: Create new version tag
        run: npx nbgv tag

      - name: Push new tag
        run: git push origin --tags
