name: New release on tag
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Build, test and release new version.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setting up node.js
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Set version
        run: npm version $(npx nbgv get-version -v NpmPackageVersion) --no-git-tag-version --allow-same-version

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Release
        if: success()
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
